---
development:
  cloud_name: dcequc9iz
  api_key: '565374223813465'
  api_secret: HifosyuxkGD6XrJWj1r7aovK5L8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dcequc9iz
  api_key: '565374223813465'
  api_secret: HifosyuxkGD6XrJWj1r7aovK5L8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dcequc9iz
  api_key: '565374223813465'
  api_secret: HifosyuxkGD6XrJWj1r7aovK5L8
  enhance_image_tag: true
  static_image_support: false
